### ISSUE TITLE
Little typo in windows build

### ISSUE THREAD

**Issue by ghost** [sizmailov/tqdm-cxx#1]
in `console_size.h` :
line 16 : `#elif defined(TQDM_ON_WINDOWS)` [not `define`]
line 17 : add `#define NOMINMAX` before `#include <windows.h>` [avoid std min/max conflict]
build and test fine on windows after that change. good job and thank you very much.

**Comment by sizmailov** [comment]
Hi, thanks for finding that! 

Typo fixed in e4e2e6a6b4f17f6bcb3238d7d975bbc141b6061f

I think `NOMINMAX` definition should go to `CMakeLIsts.txt` not to the headers. To do that I need to write a bit of CMake boilerplate to turn the repo into CMake-friendly library. I'll try to that a bit later.

**Comment by sizmailov** [comment]
On second thought in-source NOMINMAX fix sounds fine. I applied patch as you suggested.
